# **Matrix factorization for finding Hidden genres**

For this, we need to look into the rating matrix again. But now comes an additional problem. The more data we have, bigger the matrix become. And therefore computations become time consuming. In order to maintain the data features while minimizing the time consumption(computation power required), we use a technique called `Dimensional reduction`. In this notebook to separate the rating matrix into smaller parts we use a mathematical technique called `Singular Value Decomposition` (SVD).

Before going in to the mentioned topics, it is important to understand the basics of matrix factorization. Assume you have a matrix `R` and then we can decompose it in following form.

<center>

__R = U.V__
</center>

If R has dimensions n\*m then U will have n\*d and V will have d\*m dimensions. This is called `UV-Decomposition`. In recommender systems field, U is the user-feature matrix, V is the item-feature matrix and R will be the ratings matrix. The idea behind the factorization is to find values to U and V which yield their multiplication to R matrix as close as possible, in theory it is basically solving several linear equations. (ie. which satisfy the matrix multiplication.)

# SVD (Singular Value Decomposition)



One of the most common way of factorizing matrices is SVD. In SVD we construct 3 matrices namely `U`, `V* (V Transpose)` and `Σ (Sigma)`. Here U and V acts as factors while sigma acts as the regulator for the data dimensions.
<pre style='color:yellow'>
<center>M = U.Σ.V*</center>

- M  = Data Marix
- U  = User feature matrix
- Σ  = Weights diagonal matrix (eigen values matrix)
- V* = Item Feature matrix
</pre>
To get more theoritical understanding behind SVD you can watch [videos in here.](https://www.youtube.com/watch?v=gXbThCXjZFM&list=PLMrJAkhIeNNSVjnsviglFoY2nXildDCcv&index=1)

Instead of implementing myself, I have used the numpy implementation of the algorithm.

In [1]:
import pandas as pd
import numpy as np

movies = ['mib', 'st', 'av', 'b', 'ss', 'lm']
users = ['Sara', 'Jesper', 'Therese', 'Helle', 'Pietro', 'Ekaterina']
M = pd.DataFrame([
                    [5.0, 3.0, 0.0, 2.0, 2.0, 2.0],
                    [4.0, 3.0, 4.0, 0.0, 3.0, 3.0],
                    [5.0, 2.0, 5.0, 2.0, 1.0, 1.0],
                    [3.0, 5.0, 3.0, 0.0, 1.0, 1.0],
                    [3.0, 3.0, 3.0, 2.0, 4.0, 5.0],
                    [2.0, 3.0, 2.0, 3.0, 5.0, 5.0]],
                columns=movies,
                index=users)

from numpy import linalg

U, sigma, V_t = linalg.svd(M)

If we check the output from above matrices, we will see that their multiplication does not add up to the original values exactly. But close enough to be usable. Also in the sigma matrix (eigen values sorted) we can check the amount of information given by the each of the data rows/columns in the U/V matrices.

Also we can use the sigma matrix to reduce the dimensions of the matrices while retaining most of the information available on the original data. To do that we can select the most weighted values from the sigma matrix.

In [9]:
def rank_k(k):
    '''
    Function to reduce the rank to the given level
    '''
    U_reduced= np.mat(U[:,:k])
    Vt_reduced = np.mat(V_t[:k,:])
    Sigma_reduced = np.eye(k)*sigma[:k]
    
    return U_reduced, Sigma_reduced, Vt_reduced

U_reduced, Sigma_reduced, Vt_reduced = rank_k(4)
M_hat = U_reduced * Sigma_reduced * Vt_reduced

print(M_hat)

[[ 4.87147087  3.11444112  0.04893344  2.23870109  1.94083799  1.920736  ]
 [ 3.49344678  3.45787572  4.19067126  0.94886084  2.61521613  2.82032378]
 [ 5.22111879  1.8034114   4.91572235  1.58969108  1.09528095  1.14205388]
 [ 3.25351113  4.77315242  2.90384191 -0.4721446   1.14157873  1.13455568]
 [ 2.93061675  3.04700483  3.03112668  2.11137004  4.29526848  4.67079756]
 [ 2.27270952  2.76664391  1.89315701  2.50473044  4.91596291  5.35161957]]


Here based on the column and row indices,we can identfy the related ratings for a particular item. 

Also as we can see, we need to do 3 multiplications to get the M_hat matrix. To avoid that we can only save the decomposed matrices. We will take the squareroot of the Σ matrix and multiply it with each of the other matrices as below to get the decomposed matrices.

In [10]:
def rank_k_v2(k):
    '''
    Updated version of rank reduction function.
    '''
    U_reduced= np.mat(U[:,:k])
    Vt_reduced = np.mat(V_t[:k,:])
    Sigma_reduced = np.eye(k)*sigma[:k]
    Sigma_sqrt = np.sqrt(Sigma_reduced)

    return U_reduced*Sigma_sqrt, Sigma_sqrt*Vt_reduced

U_reduced, Vt_reduced = rank_k_v2(4)
M_hat = U_reduced * Vt_reduced

print(M_hat)

[[ 4.87147087  3.11444112  0.04893344  2.23870109  1.94083799  1.920736  ]
 [ 3.49344678  3.45787572  4.19067126  0.94886084  2.61521613  2.82032378]
 [ 5.22111879  1.8034114   4.91572235  1.58969108  1.09528095  1.14205388]
 [ 3.25351113  4.77315242  2.90384191 -0.4721446   1.14157873  1.13455568]
 [ 2.93061675  3.04700483  3.03112668  2.11137004  4.29526848  4.67079756]
 [ 2.27270952  2.76664391  1.89315701  2.50473044  4.91596291  5.35161957]]


But the problem in the above is that, we marked the values/ ratings we did not know with zero. It causes the decomposed matrices to generate values close to zero as well. Therefore to avoid this problem we use a technique called `Imputation`.

Basically this means that we can either normalize the each data row such that mean is zero or we can calculate the mean for each user/item and fill the null values with it. Apparently both these techniques are called Imputation methods. By doing this we can get somewhat sensible value for the null values in decomposition.

> ### __Adding new user to the decomposed matrix__

In SVD method, it is really easy to add new users to the decompsed matrix by nature. Since matrix multiplication works in a certain way, we can directly append user row to the rating (U) matrix.

<pre style='color:yellow'>
<center>u_reduced = u_original * Vt * Σ^-1</center>

here,

- u_reduced = reduced vector of user ratings.
- u_original = original ratings given by the new user.
- Vt = item Matrix transpose from SVD method.
- Σ^-1 = Inverse of the Σ matrix of SVD.

</pre>

In [11]:
from numpy.linalg import inv

# new user original ratings
u_original = np.array([4.0, 5.0, 0.0, 3.0, 3.0, 0.0])

# reduced vector
u_reduced = u_original *Vt_reduced.T* inv(Sigma_reduced)

print(u_reduced)

[[-1.45894059  0.23555071  1.9293472  -0.58325078]]


> ### __Adding new item to the decomposed matrix__

Just as we add a new user to the decomposed matrix, we can add new items to the V matrix as well.

<pre style='color:yellow'>
<center>i_reduced = i_original_t * U * Σ^-1</center>

here,

- i_reduced = the vector in the reduced space to represent the new item.
- i_original_t = original item ratings transpose vector.
- U = User Matrix from SVD method.
- Σ^-1 = Inverse of the Σ matrix of SVD.

</pre>





> One thing you might wonder is why the heck we are decomposing the matrices filled with mean values and then using the decomposed matrices to estimate the original matrix again. Answer would be, the point of decomposing is reducing the size of original matrix and extracting hidden topics for further processing.

> ## __Recommendations with SVD__

To do recommendations using SVD we can use few methods.

1. Calculate M_hat and use it to find the highest rated item for the user (which they havent consumed). (weird to me as well, apparently it works! :-/ )
2. Can use the decomposed user matrix to do the collabarative filtering
3. Using the item similarity on the decomposed item matrix.

Can test the 3 methods to see how it work.

> ## **Problems of SVD**

1. Need to fill out the empty values.
2. Slow to calculate on large matrices.
3. Even though we can add new users and items on the go, we need to recalculate the Sigma matrix often to make the decomposition accurate.
4. Not always explainable.



# Baseline Predictors

Practically speaking, Baseline predictors are type of methods that we can use for recommend items to users. 

What we do in this technique is that, we measure the inherent bias for items/ users and them use those biases as baseline for our prediction. Intuition behind baseline predictors is that if a item is considered good, its general ratings would be high. Opposite would also be true for the bad items. Also some users would be inherently highly negative/positive. In all these cases we can see some kind of bias towards a item. If we can measure this bias, it can be used as a baseline, which is what we try to do in Baseline predictors.

We use following equation as the predictor.


<pre style='color:yellow'>
<center>r_ui = µ + b_u + b_i</center>

here,

- r_ui = base prediction for item i from user u.
- µ = average of all ratings
- b_u = user bias
- b_i = item bias

</pre>

We can calculate the user bias and item bias terms using existing rating.

 1. Calculate the average of all ratings by taking sum of all elements and dividing by number of non zero elements.
 2. For the given user select a rating already given and fill the r_ui and µ values. (at this step, we know them)
 3. Do that for many items. In this way we can get many formulas.
 4. Solve those equations as a least-square problem to get the bias terms.


<center><image src="./images/Baseline predictors.jpg" width="200px" /></center>

Since this calculation is time consuming and comparatively complex, more simpler method is used as well. In this method, we first calculate the bias for each user (b_u), by taking the sum of the difference between user's ratings and the mean. Then we divide that value by number of ratings provided by user. This gives us average difference between the mean and the user's ratings.

<center><image src="./images/Baseline User bias.jpg" width="200px" /></center>

Then after calculating biases for all users we can calculate items biases in the same way as below.

<center><image src="./images/Baseline Item bias.jpg" width="200px" /></center>

Those above values can be used instead of using imputation methods, to make any matrix factorization method to work better. Below is a sample implementation of the related calculations.


In [29]:
global_mean = M[M>0].mean().mean()  #To calculate the global mean of matrix values
M_minus_mean = M[M>0] - global_mean  # r_iu - global mean
user_bias = M_minus_mean.T.mean()
item_bias = M_minus_mean.apply(lambda r: r - user_bias).mean()

In [30]:
M_minus_mean

mib        st        av         b        ss        lm
Sara       2.002778  0.002778       NaN -0.997222 -0.997222 -0.997222
Jesper     1.002778  0.002778  1.002778       NaN  0.002778  0.002778
Therese    2.002778 -0.997222  2.002778 -0.997222 -1.997222 -1.997222
Helle      0.002778  2.002778  0.002778       NaN -1.997222 -1.997222
Pietro     0.002778  0.002778  0.002778 -0.997222  1.002778  2.002778
Ekaterina -0.997222  0.002778 -0.997222  0.002778  2.002778  2.002778

In [31]:
user_bias

Sara        -0.197222
Jesper       0.402778
Therese     -0.330556
Helle       -0.397222
Pietro       0.336111
Ekaterina    0.336111
dtype: float64

In [32]:
item_bias

mib    0.644444
st     0.144444
av     0.333333
b     -0.783333
ss    -0.355556
lm    -0.188889
dtype: float64

Above values show the bias values for respective items and users. We can see Sara has generally negetive bias and Jesper has positive rating bias. By looking at the original ratings given by those 2 users, we can verify this as well.

> Also one other factor we need to consider here is time. User and item biases may change over time and therefore we need to consider it to make the predictions more accurate. (We can use weighted averages etc.)

# Funk SVD (Regularized SVD)

This algorithm was developed to fix some of the problems of SVD, mainly to work with sparse matrix (where number of filled values are low). In Funk SVD, we use RMSE along with gradient descent to approach a better matrix factorization.

> ### Root Mean Squared Error

> In the context of user rating and item rating matrix multiplication, we assume that those two create the rating matrix. So RMSE would be a value related to the summation of difference between the actual rating and the values got multiplied from the rating/item matrices.

<center><image src="./images/RMSE baseline.jpg" width="200px" /></center>

> Here `u` means user matrix u row and `i` means item matrix i'th column, which depicts the r_hat in the (u,i) position M_hat matrix.

Then we use gradient descent to minimize the above value.


> ### Gradient Descent

> This very well known method in ML. Basically we start in a random position of the output and go through the lowest gradient direction which would minimize the RMSE. Read it in either ML related book or statistic book for more information.

In funk SVD there's no sigma matrix. Instead we directly have 2 matrices. Therefore we first need to figure out number of features we need to keep in the factorized form. This is usually done by running the algorithm for several different number of features and selecting the best value. Also it is worth noting that bias terms are also considered when estimating the factorizations.

When predicting using Funk SVD, we can use the same techniques as the normal SVD without an issue.


In [1052]:
def predict(user, item):
    avg = all_movies_mean
    pq = np.dot(item_factors[item], user_factors[user].T)
    b_ui = avg + user_bias[user] + item_bias[item]
    prediction = b_ui + pq

    return prediction

In [1053]:
def stocastic_gradient_descent(index_randomized, ratings):
    mse = 0
    
    for inx in index_randomized:
        rating_row = ratings[inx]
        u = inx

        item_randomized = random.sample(range(0, len(rating_row)), len(rating_row))
        
        for i in item_randomized:
            rating = rating_row[i]
            prediction = predict(u, i)
            
            err = (rating - prediction)

            user_bias[u] += b_lr * (err - bias_r * user_bias[u])
            item_bias[i] += b_lr * (err - bias_r * item_bias[i])

            user_fac = user_factors[u]
            item_fac = item_factors[i]
            
            user_factors[u] +=  lr * (err * item_fac
                                                - r * user_fac)
            item_factors[i] +=  lr * (err * user_fac
                                                - r * item_fac)

            # Calculating RMSE
            mse += (err) ** 2

    return (mse)

In [1054]:
from collections import defaultdict

k = 3  # Number of features to keep in the factorized matrices

movies = ['mib', 'st', 'av', 'b', 'ss', 'lm']
users = ['Sara', 'Jesper', 'Therese', 'Helle', 'Pietro', 'Ekaterina']
M = np.array([
                    [5.0, 3.0, 0.0, 2.0, 2.0, 2.0],
                    [4.0, 3.0, 4.0, 0.0, 3.0, 3.0],
                    [5.0, 2.0, 5.0, 2.0, 1.0, 1.0],
                    [3.0, 5.0, 3.0, 0.0, 1.0, 1.0],
                    [3.0, 3.0, 3.0, 2.0, 4.0, 5.0],
                    [2.0, 3.0, 2.0, 3.0, 5.0, 5.0]]
                )

item_factors = np.random.uniform(size=(len(movies), k))
user_factors = np.random.normal(size=(len(users), k))

all_movies_mean = M[M>0].mean().mean() 

user_bias = defaultdict(lambda: 0)
item_bias = defaultdict(lambda: 0)

In [1055]:
import random
from datetime import datetime

iterations = 0
last_err = 0
iteration_err = sys.maxsize
finished = False

lr      = 0.05
b_lr    = 0.01
r       = 0.001
bias_r  = 0.001

        
while not finished:

    index_randomized = random.sample(range(0, len(M)), len(M))

    iteration_err = stocastic_gradient_descent( index_randomized,
                                                M)

    if(iterations%10==0):
        print(iteration_err)

    iterations += 1
    if(iterations >= 100):
        break
                        
    last_err = iteration_err


100.07094850033116
24.16643649902043
10.466719350275437
5.976312908919969
4.744028823950094
4.289225986111172
4.106737963987126
4.037670240023444
3.9814951536063043
3.949055008435495


In [1056]:
temp = np.dot(item_factors, user_factors.T).T

In [1057]:
user_bias[0]

-0.14336531811425812

In [1058]:
item_bias[0]

0.4797200154460631

In [1059]:
(temp[0] + user_bias[0] + item_bias[0] + all_movies_mean)

array([4.83187567, 3.767716  , 0.2096792 , 3.92966637, 2.33925628,
       2.08336076])

In [1060]:
M[0]

array([5., 3., 0., 2., 2., 2.])

Therefore we can observe that, decomposed matrices and biased terms somewhat converge to the original data matrix. But there are several concerns to be addressed. In some scenarios, there may be unexplainable ratings can be observed. This is due to large negative/positive bias terms compared to ratings. We need to fix the solution to address it. Also it is required to fine tune the parameters to get the best results which can be exhausting and time consuming.